version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8.15
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      # - run:
      #     name: Install Git and OpenSSH
      #     command: apk add git openssh
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "henrik.raitasola@gmail.com"
            git config user.name "henrikra"
      - add_ssh_keys:
          fingerprints:
            - "78:d6:54:89:13:e4:24:50:d1:82:35:79:69:f0:1e:d6"
      - run:
          name: Run build and deploy
          command: npm run deploy

workflows:
  version: 2
  install_build_deploy:
    jobs:
      - deploy
