version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8.15
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Add .env
          command: echo REACT_APP_TMDB_API_KEY=$REACT_APP_TMDB_API_KEY
      - add_ssh_keys:
          fingerprints:
            - "da:56:aa:36:74:60:e2:b0:13:53:50:8b:50:8c:4f:ac"
      - run:
          name: Run build and deploy
          command: npm run deploy

workflows:
  version: 2
  install_build_deploy:
    jobs:
      - deploy
