version: 2
jobs:
  build:
    docker:
      - image: node:8.15.0-alpine
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm ci
      - run:
          name: Run build
          command: npm run build
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy deployment bracnch to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git heroku-deployment-from-circle

workflows:
  version: 2
  install_build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: heroku-deployment-from-circle

