version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - node_modules
  deploy:
    docker:
      - image: circleci/node:8.15
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Add .env
          command: echo REACT_APP_TMDB_API_KEY=$REACT_APP_TMDB_API_KEY
      - run:
          name: Setup Git user
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
      - add_ssh_keys:
          fingerprints:
            - "da:56:aa:36:74:60:e2:b0:13:53:50:8b:50:8c:4f:ac"
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  install_build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: deploy-gh-page-from-circleci
