version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - build
  deploy:
    docker:
      - image: circleci/node:8.15
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Add .env
          command: echo REACT_APP_TMDB_API_KEY=$REACT_APP_TMDB_API_KEY
      - run:
          name: Add githu stuff
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
      - add_ssh_keys:
          fingerprints:
            - "da:56:aa:36:74:60:e2:b0:13:53:50:8b:50:8c:4f:ac"
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  install_build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: deploy-gh-page-from-circleci
