version: 2
jobs:
  deploy-job:
    docker:
      - image: node:8.15.0-alpine
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm ci
      - run:
          name: Run build and deploy
          command: npm run deploy
      - add_ssh_keys:
          fingerprints:
            - "d7:68:22:80:86:16:92:1e:6c:e6:be:9b:65:3d:ef:58"
      
workflows:
  version: 2
  install_build_deploy:
    jobs:
      - deploy-job

